
menu:
- {lang: en, name: 'Programming', path: 'menu', url: 'programming.html'}
- {lang: de, name: 'Programmierung', path: 'menu', url: 'programming-de.html'}
- {lang: en, name: 'Internet of things', path: 'menu', url: 'iot.html'}
- {lang: de, name: 'Internet der Dinge', path: 'menu', url: 'iot-de.html'}
- {lang: en, name: 'Meta', path: 'menu', url: 'blogging.html'}
- {lang: de, name: 'Meta', path: 'menu', url: 'blogging-de.html'}
- {lang: en, name: 'Contact', path: 'menu', url: 'contact.html'}
- {lang: de, name: 'Kontakt', path: 'menu', url: 'contact-de.html'}

email: inbox@jakobmeier.ch

git_repository_root_url: https://github.com/jakmeier/www.jakobmeier.ch/tree/gh-pages/ 

# Used for jmr-analytics, a sort of minimalistic custom analytics tool. Each page will simulate a click on a link in the form BASEURL{{page.ref}} on each load. This can be used to track viewer statics in a external service.
jmr_analytics_base_url: https://bit.ly/2MAMZt-jmr-analytics-

# Customize site text

TEXTS:
  site:
    home_file:
      en: index.html
      de: index-de.html
    title:
      en: Jakob's Blog 
      de: Jakobs Blog
    description:
      en: Technologies in practice
      de: Technologien praktisch angewandt
    author:
      en: 'Jakob Meier'
      de: 'Jakob Meier'
  read_more: 
    en: 'Read more'
    de: 'Mehr lesen'
  next_page: 
    en: 'Newer'
    de: 'Nächster Beitrag'
  previous_page: 
    en: 'Older'
    de: 'Vorheriger Beitrag'
  posts: 
    en: 'Posts'
    de: 'Beiträge'
  related_posts: 
    en: 'You may also enjoy:'
    de: 'Ähnliche Beiträge:'
  post_date_prefix: 
    en: 'Written on'
    de: 'Verfasst am'
  post_date_postfix: 
    en: 'by'
    de: 'von'
  en:
    en: 'English'
    de: 'Englisch'
  de: 
    en: 'German'
    de: 'Deutsch'
  less-than-a-minute:
    en: less than 1 minute read
    de: weniger als 1 Minute zum Lesen
  one-minute-read:
    en: 1 minute read
    de: 1 Minute zum Lesen
  minutes-to-read:
    en: minutes read
    de: Minuten zum Lesen
  tech-stack:
    en: Technology stack
    de: Technologien in diesem Beitrag
  next-in-series:
    en: Next post in series
    de: Nächster Beitrag in dieser Serie