# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

#google-ID: 'UA-112060364-1'

menu:
- {lang: English, name: 'About', path: 'menu', url: 'about.html'}
- {lang: Deutsch, name: 'Über mich', path: 'menu', url: 'about-de.html'}
- {lang: English, name: 'Contact', path: 'menu', url: 'contact.html'}
- {lang: Deutsch, name: 'Kontakt', path: 'menu', url: 'contact-de.html'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
