[package]
name = "nuts-example-0"
version = "0.1.0"
authors = ["Jakob Meier <mail@jakobmeier.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nuts = "0.2.1"